apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: octopus-kubectl
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      name: octopus-kubectl
      namespace: ${NAMESPACE}
      labels: 
        app: octopus-kubectl
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"lifecycle", "value":"spot"}]'
    spec:
      serviceAccountName: ${SERVICEACCOUNT}
      containers:
      - name: octopus-kubectl
        image: whereisaaron/octopus-kubectl:latest
        imagePullPolicy: Always
        env:
        - name: HELM_HOST
          value: "${HELM_HOST}"
        ports:
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: ssh-volume
          mountPath: /root/.ssh
        - name: aws-volume
          mountPath: /root/.aws
        lifecycle:
          postStart:
            exec:
              command:
              - "chmod"
              - "0700"
              - "/root/.ssh"
              - "/root/.aws"
      volumes:
      - name: ssh-volume
        secret:
          secretName: octopus-kubectl
          items:
          - key: authorized_keys
            path: authorized_keys
      - name: aws-volume
        secret:
          secretName: octopus-kubectl
          items:
          - key: credentials
            path: credentials
---
apiVersion: v1
kind: Service
metadata:
  name: octopus-kubectl
  namespace: ${NAMESPACE}
  labels:
    app: octopus-kubectl
spec:
  selector:
    app: octopus-kubectl
  ports:
    - name: ssh
      nodePort: ${NODEPORT}
      port: 22
      targetPort: ssh
  type: NodePort
