apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: octopus-kubectl
  namespace: $NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      name: octopus-kubectl
      namespace: $NAMESPACE
      labels: 
        app: octopus-kubectl
    spec:
      serviceAccountName: $SERVICEACCOUNT
      containers:
      - name: octopus-kubectl
        image: whereisaaron/octopus-kubectl:latest
        ports:
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: config-volume
          mountPath: /root/.ssh
        lifecycle:
          postStart:
            exec:
              command:
              - "chmod"
              - "0700"
              - "/root/.ssh"
      volumes:
      - name: config-volume
        configMap:
          name: octopus-kubectl
          items:
          - key: authorized-keys
            path: authorized_keys
---
apiVersion: v1
kind: Service
metadata:
  name: octopus-kubectl
  namespace: $NAMESPACE
spec:
  selector:
    app: octopus-kubectl
  ports:
    - name: ssh
      nodePort: $NODEPORT
      port: 22
      targetPort: ssh
  type: NodePort
